import type { PrismaClient, RoleType } from "@prisma/client";
import { insertAllIfNotExists } from "./upsert";

export async function seed(prisma: PrismaClient) {
  await insertAllIfNotExists(prisma.teamRole.upsert, [
    {
      id: 1,
      title: "Bureau",
      type: "Main" as RoleType,
      order: 1,
      createdById: "-1",
    },
    {
      id: 2,
      title: "Président[,e]",
      type: "Main" as RoleType,
      parentId: 1,
      order: 1,
      createdById: "-1",
    },
    {
      id: 3,
      title: "Secrétaire Général[,e]",
      type: "Main" as RoleType,
      parentId: 1,
      order: 2,
      createdById: "-1",
    },
    {
      id: 4,
      title: "Trésori[er,ère]",
      type: "Main" as RoleType,
      parentId: 1,
      order: 3,
      createdById: "-1",
    },
    {
      id: 5,
      title: "Secrétaire Général[,e]  Adjoint[,e]",
      type: "Main" as RoleType,
      parentId: 1,
      order: 4,
      createdById: "-1",
    },
    {
      id: 6,
      title: "Trésori[er,ère] Adjoint[,e]",
      type: "Main" as RoleType,
      parentId: 1,
      order: 5,
      createdById: "-1",
    },
    {
      id: 7,
      title: "Vice-présidents",
      type: "Main" as RoleType,
      order: 3,
      createdById: "-1",
    },
    {
      id: 8,
      title: "Vice-Président[,e] Secteur Alsace",
      type: "Main" as RoleType,
      parentId: 7,
      order: 1,
      createdById: "-1",
    },
    {
      id: 9,
      title: "Vice-Président[,e] Secteur Champagne-Ardenne",
      type: "Main" as RoleType,
      parentId: 7,
      order: 2,
      createdById: "-1",
    },
    {
      id: 10,
      title: "Vice-Président[,e] Secteur Lorraine",
      type: "Main" as RoleType,
      parentId: 7,
      order: 3,
      createdById: "-1",
    },
    {
      id: 11,
      title: "Arbitres",
      type: "Commission" as RoleType,
      order: 1,
      createdById: "-1",
    },
    {
      id: 12,
      title: "Médicale",
      type: "Commission" as RoleType,
      order: 2,
      createdById: "-1",
    },
    {
      id: 13,
      title: "Structuration et labellisation",
      subtitle: "1 référent par département",
      type: "Commission" as RoleType,
      order: 3,
      createdById: "-1",
    },
    {
      id: 14,
      title: "Formation",
      type: "Commission" as RoleType,
      order: 4,
      createdById: "-1",
    },
    {
      id: 15,
      title: "Calendrier",
      subtitle: "1 référent par département",
      type: "Commission" as RoleType,
      order: 5,
      createdById: "-1",
    },
    {
      id: 16,
      title: "Projets et conseils",
      type: "Commission" as RoleType,
      order: 6,
      createdById: "-1",
    },
    {
      id: 17,
      title: "Développement et communication",
      type: "Commission" as RoleType,
      order: 7,
      createdById: "-1",
    },
    {
      id: 18,
      title: "Promotion du tir à l'arc",
      type: "Commission" as RoleType,
      order: 8,
      createdById: "-1",
    },
    {
      id: 19,
      title: "Sportive",
      type: "Commission" as RoleType,
      order: 9,
      createdById: "-1",
    },
    {
      id: 20,
      title: "Adultes",
      subtitle: "Salle, TAE, DR",
      type: "Commission" as RoleType,
      parentId: 19,
      order: 1,
      createdById: "-1",
    },
    {
      id: 21,
      title: "Jeunes",
      subtitle: "UNSS, FSU, Pôle régional",
      type: "Commission" as RoleType,
      parentId: 19,
      order: 2,
      createdById: "-1",
    },
    {
      id: 22,
      title: "Parcours",
      subtitle: "CAMPAGNE, 3D, NATURE",
      type: "Commission" as RoleType,
      parentId: 19,
      order: 3,
      createdById: "-1",
    },
    {
      id: 23,
      title: "Traditions",
      subtitle: "BEURSAULT, BOUQUET PROVINCIAL",
      type: "Commission" as RoleType,
      parentId: 19,
      order: 4,
      createdById: "-1",
    },
    {
      id: 24,
      title: "Para archerie",
      subtitle: "FFH et FFSA",
      type: "Commission" as RoleType,
      parentId: 19,
      order: 5,
      createdById: "-1",
    },
    {
      id: 25,
      title: "Sport Santé",
      subtitle: "Sport sur ordonnance",
      type: "Commission" as RoleType,
      parentId: 19,
      order: 6,
      createdById: "-1",
    },
    {
      id: 26,
      title: "Les Conseillers Techniques",
      type: "Commission" as RoleType,
      order: 10,
      createdById: "-1",
    },
  ]);
}
